### ISSUE TITLE
`fade-transition` not a `field-element?`

### ISSUE THREAD

**Issue by stchang** [LeifAndersen/racket-video-backup#47]
Should this work?
```racket
(playlist (color "green" #:length 20) (color "red" #:length 20)
          #:transitions (list (fade-transition #:length 15)))
```

It currently gives the error:
```
playlist: contract violation
  expected: field-element?
  given: (transition '#hash() #<procedure:mlt-prop-default-proc> '() 'luma #f 15)
```

For reference, this works:
```racket
(playlist (color "green" #:length 20)
          (fade-transition #:length 15)
          (color "red" #:length 20))
```

**Comment by LeifAndersen** [comment]
The first one should _not_ work, and the second one _should_ work.

However, it should give a much better error message.

The reason why it doesn't work is because transitions can be used in inline position, or in refereed position. If its inline (as it is in the second case), then no #:start #:end producers are needed, but if its in the referred position, start and end producers must be explicitly specified.

As such, this _should_ work:

```
(define green (color "green" #:length 20))
(define red (color "red" #:length 20))
(playlist green red
          #:transitions (list (fade-transition #:length 15 #:start green #:end red)))
```

**Comment by stchang** [comment]
ok thanks.

**Comment by LeifAndersen** [comment]
I am actually going to reopen this issue because it needs to produce a better error message.
